### ISSUE TITLE
add flutter_blue is error for iOS

### ISSUE THREAD

**Issue by LiangLuDev** [pauldemarco/flutter_blue#319]
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_blue: '^0.6.0'
```

```
pod version:1.7.4
xcode :9.2
flutter :1.7.8
```

iOS：
I created a new project and added it,but is error “ 'flutter_blue/FlutterBluePlugin.h' file not found”。
