### ISSUE TITLE
blutter blue for macos

### ISSUE THREAD

**Issue by ekuleshov** [pauldemarco/flutter_blue#463]
With Flutter 1.12 adding macos target as beta, it would be great to have macos support in flutter blue.

**Comment by xvrh** [comment]
I tried this quickly and this is actually easy to add. 
The whole iOS code can be reused to run on macOS

Instructions:
- Copy/paste the `ios` folder in a `macos` folder
- In `FlutterBluePlugin`, change the import `<Flutter/Flutter.h>` to `<FlutterMacOS/FlutterMacOS.h>`
- Change the flutter section in the pubspec.yaml  to:
```yaml
flutter:
  plugin:
    platforms:
      android:
        package: com.pauldemarco.flutterblue
        pluginClass: FlutterBluePlugin
      ios:
        pluginClass: FlutterBluePlugin
      macos:
        pluginClass: FlutterBluePlugin
```
- In the target application project, open the macos folder in XCode and in Runner > Signing & Capabilities > App Sandbox > check Bluetooth.
