### ISSUE TITLE
compatible library bug

### ISSUE THREAD

**Issue by anoobishnoob** [pauldemarco/flutter_blue#501]
I keep getting this error in my console after creating my first instance of flutterblue. This is my home page where I am making the call 

```
import 'package:flutter/material.dart';
import 'package:provider/provider.dart';
import 'package:flutter_blue/flutter_blue.dart';

import 'auth.dart';

class HomePage extends StatefulWidget {
  @override
  _HomePageState createState() => _HomePageState();
}

class _HomePageState extends State<HomePage> {
  FlutterBlue flutterBlue = FlutterBlue.instance;
  @override
  Widget build(BuildContext context) {
    return Scaffold(
      appBar: AppBar(
        title: Text("Home Flutter Firebase"),
        //actions: <Widget>[LogoutButton()],
      ),
      body: Center(
        child: Column(
          children: <Widget>[
            Text('Connect with Bluetooth'),
            SizedBox(height: 20.0),
            RaisedButton(
                child: Text("LOGOUT"),
                onPressed: () async {
                  await Provider.of<AuthService>(context).logout();

                  //Navigator.pushReplacementNamed(context, "/");
                }),
            RaisedButton(
                child: Text("CONNECT TO BLUETOOTH"),
                onPressed: () async {
                  //await flutterBlue.startScan(timeout: Duration(seconds: 4));

                  //Navigator.pushReplacementNamed(context, "/");
                }),
          ],
        ),
      ),
    );
  }
}

```

Here is the android manifest where I did make the changes suggested in the console error.
```

<manifest xmlns:android="http://schemas.android.com/apk/res/android"
    package="com.example.simple_firebase_auth">
    <uses-sdk android:minSdkVersion="19"
        android:targetSdkVersion="28"
        android:maxSdkVersion="29" />


    <!-- io.flutter.app.FlutterApplication is an android.app.Application that
         calls FlutterMain.startInitialization(this); in its onCreate method.
         In most cases you can leave this as-is, but you if you want to provide
         additional functionality it is fine to subclass or reimplement
         FlutterApplication and put your custom class here. -->

    <application
        android:name="io.flutter.app.FlutterApplication"
        android:label="simple_firebase_auth"
        android:icon="@mipmap/ic_launcher">
        <activity
            android:name=".MainActivity"
            android:launchMode="singleTop"
            android:theme="@style/LaunchTheme"
            android:configChanges="orientation|keyboardHidden|keyboard|screenSize|locale|layoutDirection|fontScale|screenLayout|density|uiMode"
            android:hardwareAccelerated="true"
            android:windowSoftInputMode="adjustResize"
            >
            <!-- This keeps the window background of the activity showing
                 until Flutter renders its first frame. It can be removed if
                 there is no splash screen (such as the default splash screen
                 defined in @style/LaunchTheme). -->
            <meta-data
                android:name="io.flutter.app.android.SplashScreenUntilFirstFrame"
                android:value="true" />
            <intent-filter>
                <action android:name="android.intent.action.MAIN"/>
                <category android:name="android.intent.category.LAUNCHER"/>
            </intent-filter>
        </activity>
    </application>
</manifest>

```
Also here is the pubspec.yaml just in case it is something there 

```

name: simple_firebase_auth
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2
  provider: 2.0.1
  flutter_blue: ^0.6.3+1


dev_dependencies:
  flutter_test:
    sdk: flutter


# For information on the generic Dart part of this file, see the
# following page: https://www.dartlang.org/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:


  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
    uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  # assets:
  #  - images/a_dot_burr.jpeg
  #  - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages

```

I am probably forgetting something crucial, but I'd rather just put this up because this seems to be a very simple error that can be made.

> 
> C:\Users\sqandil\Downloads\simple_firebase_auth-completed-part-one\simple_firebase_auth-completed-part-one\android\app\src\debug\AndroidManifest.xml:3:5-5:38 Error:
> 	uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_blue] C:\Users\sqandil\Downloads\simple_firebase_auth-completed-part-one\simple_firebase_auth-completed-part-one\build\flutter_blue\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml as the library might be using APIs not available in 16
> 	Suggestion: use a compatible library with a minSdk of at most 16,
> 		or increase this project's minSdk version to at least 19,
> 		or use tools:overrideLibrary="com.pauldemarco.flutter_blue" to force usage (may lead to runtime failures)
> 
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':app:processDebugManifest'.
> > Manifest merger failed : uses-sdk:minSdkVersion 16 cannot be smaller than version 19 declared in library [:flutter_blue] C:\Users\sqandil\Downloads\simple_firebase_auth-completed-part-one\simple_firebase_auth-completed-part-one\build\flutter_blue\intermediates\merged_manifests\debug\processDebugManifest\merged\AndroidManifest.xml as the library might be using APIs not available in 16
>   	Suggestion: use a compatible library with a minSdk of at most 16,
>   		or increase this project's minSdk version to at least 19,
>   		or use tools:overrideLibrary="com.pauldemarco.flutter_blue" to force usage (may lead to runtime failures)
> 
> * Try:
> Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.
> 
> * Get more help at https://help.gradle.org
> 
> BUILD FAILED in 14s
> Finished with error: Gradle task assembleDebug failed with exit code 1
>
