### ISSUE TITLE
pub get failed  - Is there a workaround to install the latest version somehow?

### ISSUE THREAD

**Issue by phev8** [pauldemarco/flutter_blue#99]
Hello,

I included the package into a project with freshly installed flutter (Flutter Release Preview 1 - 0.5.1), and I get the following error message:

     Because every version of flutter_test from sdk depends on convert 2.0.1 and flutter_blue 0.4.0 depends on convert ^2.0.2, flutter_test from sdk is incompatible with flutter_blue 0.4.0.

pubspec.yaml is generated by 'flutter create myapp' and I've just added flutter_blue: ^0.4.0 into the dependencies

Is there any solution/workaround for this problem.

**Comment by nhardt** [comment]
A general flutter solution is to use dependency overrides.

https://www.dartlang.org/tools/pub/dependencies#dependency-overrides

in pubspec.yaml:
```
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^0.1.2
  flutter_blue: ^0.4.0

dependency_overrides:
  convert: ^2.0.2
```
